spring:
  application:
    name: client-server1
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: client-server1
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8090/eureka/
