version: '3'

services:
  eureka-server:
     image: 239206511/eureka-server:v1.0.0
     deploy:
       replicas: 1
       update_config:
         parallelism: 2
         delay: 10s
       restart_policy:
         condition: on-failure
     hostname: eureka-server
     container_name: eureka-server
     ports:
       - "8090:8090"
     volumes:
       - /etc/timezone:/etc/timezone
       - /etc/localtime:/etc/localtime
     networks:
       - swarm-example

  config-server:
     image: 239206511/config-server:v1.0.0
     deploy:
       replicas: 1
       update_config:
         parallelism: 2
         delay: 10s
       restart_policy:
         condition: on-failure
     hostname: config-server
     container_name: config-server
     ports:
        - "8082:8082"
     depends_on:
        - eureka-server
     volumes:
       - /etc/timezone:/etc/timezone
       - /etc/localtime:/etc/localtime
     networks:
       - swarm-example

  zuul-gateway:
     image: 239206511/zuul-gateway:v1.0.0
     deploy:
       replicas: 1
       update_config:
         parallelism: 2
         delay: 10s
       restart_policy:
         condition: on-failure
     hostname: zuul-gateway
     container_name: zuul-gateway
     ports:
       - "8083:8083"
     depends_on:
       - eureka-server
     volumes:
       - /etc/timezone:/etc/timezone
       - /etc/localtime:/etc/localtime
     networks:
       - swarm-example

  client-server1:
     image: 239206511/client-server1:v1.0.0
     deploy:
       replicas: 1
#       placement:
#         constraints: [node.role == manager]
       update_config:
         parallelism: 2
         delay: 10s
       restart_policy:
         condition: on-failure
     hostname: client-server1
     container_name: client-server1
     ports:
       - "8081:8081"
     depends_on:
       - eureka-server
       - config-server
     volumes:
       - /etc/timezone:/etc/timezone
       - /etc/localtime:/etc/localtime
     networks:
       - swarm-example

  client-server2:
     image: 239206511/client-server2:v1.0.0
     deploy:
       replicas: 1
       update_config:
         parallelism: 2
         delay: 10s
       restart_policy:
         condition: on-failure
     hostname: client-server2
     container_name: client-server2
     ports:
       - "8084:8084"
     depends_on:
       - eureka-server
       - config-server
     volumes:
       - /etc/timezone:/etc/timezone
       - /etc/localtime:/etc/localtime
     networks:
       - swarm-example

networks:
  swarm-example:
    driver: overlay