spring:
  application:
    name: config-server
server:
  port: 8082
  cloud:
    config:
      server:
        git:
          uri: https://github.com/love-mh-forever/spring-cloud-examples.git
          search-paths: spring-cloud-swarm/conf
          username: love-dl-forever                                        # git仓库的账号
          password: a810095178
          timeout: 2000
                                               # git仓库的密码
        native:
          search-locations: conf
        bootstrap: true   #项目的相对路径

  profiles:
    active: git
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8090/eureka/
