spring:
  application:
    name: eureka-server
server:
  port: 8090
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/

