server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/love-dl-forever/spring-cloud-starter/    # 配置git仓库的地址
          search-paths: neo-config,*/application.properties                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: love-dl-forever                                        # git仓库的账号
          password: a810095178                                     # git仓库的密码

        native:
          search-locations: /work/neo-config      #neo-config在本地的相对路径
  profiles: 
    active: native
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址
